### ISSUE TITLE
uncaught exception: undefined

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/search-for-kirby#13]
While testing the search with the `sqlite` provider in the panel, I noticed that each time I click on a search result, I get the following error in the console:

    uncaught exception: undefined

Nothing more specific, no file and line references.
There are no visual issues in the UI where everything seems to be just working fine.

This is in Firefox 72.0.2 on macOS Catalina.

**Comment by distantnative** [comment]
I think this related to a bug int he Kirby core: https://github.com/getkirby/kirby/issues/2666
