### ISSUE TITLE
TypeError in site-context

### ISSUE THREAD

**Issue by hannesherold** [distantnative/search-for-kirby#25]
## Describe the bug
When a field of `type: text` is available in `site.yml`, trying to save changes to that field in the panel throws an error:

```
Exception: TypeError
Argument 1 passed to Kirby\Search\Index::update() must be of the type string, null given, called in /public/site/plugins/search/src/config/hooks.php on line 16
```

## Steps to reproduce

1. Install the plugin
2. Create a standard text field in `site.yml`
3. Type some text into that field using the panel
4. Save changes

## Additional context

Error seems to occur in site-context only. 

## Specifications

  - Plugin version: 1.0.0
  - Kirby version: 3.4.3

**Comment by distantnative** [comment]
Falsely added a hook for site.

✅ Has been removed in upcoming 1.1
