### ISSUE TITLE
Finalize v1.1 ands docs (when Kirby 3.5 is out)

### ISSUE THREAD

**Issue by distantnative** [distantnative/search-for-kirby#34]

**Comment by hannesherold** [comment]
It's probably already on your list, but it would be helpful if you could describe the available options for the search method. At first I just missed the `limit` option and didn't know that it defaults to 10 results.

Also good to know how to combine this with the new `operator` when working with SQLite.

Example:

    $results = collection('bestand')->search($query, [
	    'operator' => 'AND',
	    'limit' => 100
    ]);

**Comment by yoanmalie** [comment]
Hello @distantnative Does it work with the builder (plugin and/or the 3.5 native)? I can't find some content that came from textarea fields inside the builder. The config setting are by default.

**Comment by distantnative** [comment]
@yoanmalie replied on Discord.

✅ Will be included in the docs alongside 1.1.0 release this week.
