### ISSUE TITLE
Develop-branch: Return value of Kirby\Cms\App::root() must be of the type string, null returned

### ISSUE THREAD

**Issue by hannesherold** [distantnative/search-for-kirby#35]
Using the `develop`-branch, there's an error when trying to create the index from the command line:

    Loading Kirby...
    Reindexing using the Search plugin...
    TypeError: Return value of Kirby\Cms\App::root() must be of the type string, null returned in file /Users/user/plainkit/kirby/src/Cms/App.php on line 1136
    Stack trace:
      1. TypeError->() /Users/user/plainkit/kirby/src/Cms/App.php:1136
      2. Kirby\Cms\App->root() /Users/user/plainkit/site/plugins/search/src/models/Providers/Sqlite.php:67
      3. Kirby\Search\Providers\Sqlite->defaults() /Users/user/plainkit/site/plugins/search/src/models/Provider.php:67
      4. Kirby\Search\Provider->setOptions() /Users/user/plainkit/site/plugins/search/src/models/Providers/Sqlite.php:37
      5. Kirby\Search\Providers\Sqlite->\_\_construct() /Users/user/plainkit/site/plugins/search/src/models/Index.php:50
      6. Kirby\Search\Index->\_\_construct() /Users/user/plainkit/site/plugins/search/bin/index:24

Same error with `$results = $site->search($query);`

In the panel section : `Invalid section type ("search“)`

The config file of the plainkit:

    <?php
    
    return [
      'debug'  => true, 
      'search' => [
        'provider' => 'sqlite',
        'sqlite' => [
          'fuzzy' => false,
        ]
      ]
    ];

## Specifications

  - Plugin version: 1.0.0 develop-branch
  - Kirby version: 3.4.4 (plainkit)
  - Browser: Chrome latest

**Comment by distantnative** [comment]
Ah sorry, I didn't really that earlier: I'm building v1.1 to be based on Kirby 3.5 - which features a new `logs` root. And that's exactly that I am calling there but because you are on 3.4.4 it crashes.

For testing, you could either run Kirby on its `features` branch. Or you edit the line 67 in `site/plugins/search/src/models/Providers/Sqlite.php` from

```php
            'file'     => kirby()->root('logs') . '/search/index.sqlite',
```

to 

```php
            'file'    => dirname(__DIR__, 5) . '/logs/search/index.sqlite',
```

The missing Panel section will return before the v1.1 release.

**Comment by hannesherold** [comment]
I see, thank you! Replaced the line, now it works.
