### ISSUE TITLE
Japanese support? 

### ISSUE THREAD

**Issue by RickCogley** [distantnative/search-for-kirby#45]
Hi - just wondering, does your search plugin, in its standard setup, work for CJK languages? Japanese, for instance, doesn't use spaces, so search engines have to index content a bit differently from languages that use spaces between words. 

(I see I can use algolia, and I know that indexes Japanese (and CJK generally), but I just wanted to ask if the standard flavor will work for non-space-y languages). 

Thanks in advance.

**Comment by distantnative** [comment]
Hi @RickCogley , I have no experience with languages like these and the plugin. I would assume the sqlite provider won't work for the reasons you outlined. So using Algolia might be the better choice since you state that Algolia supports these.

**Comment by RickCogley** [comment]
Thanks for the answer @distantnative. If I try it, I'll try algolia then :-)
