### ISSUE TITLE
Setting ['operator' => 'AND'] has no effect

### ISSUE THREAD

**Issue by bvrp** [distantnative/search-for-kirby#47]
setting up the plugin for first time.

For the following-

$results = $site->search( $query, ['operator' => 'AND' , 'limit' => 50 ] );

operator=>'AND' has no effect.

Searches consisting of two words return nothing. Single term searches are working as expected. As is the 'limit' option.

**Comment by psntr** [comment]
@bvrp did you manage to solve this? I'm having same issue, the operator has no effect.

**Comment by bvrp** [comment]
Hi, no I did not. Seems that everything distantnative has on here for Kirby is broken in one way or another.

So I "solved" it by just making my own index and search script.

**Comment by distantnative** [comment]
@psntr can you confirm that you're using the SQLite provider and not algolia?

> Seems that everything distantnative has on here for Kirby is broken in one way or another.

While I sadly cannot dispute this factually, I would like you @bvrp to consider what you cause with such a passive-aggressive comment on a product that is offered for free and created in my spare time. Which unfortunately has been way to limited to give good support and to fix all bugs in the last months, that's fact. But I really didn't appreciate this comment and you can reflect on if that's the way you want to interact with open source developers.

**Comment by bvrp** [comment]
distantnative, give me a break.

If you are going to put something out there, you should do it in a manner that doesn't waste people's time. This should go without saying. Do it in a manner where you actually address people's reports of issues (that they took time out to bring forward) instead of ignoring them.

The Kirby CMS (a commercial product btw) lists these plugins as part of their ecosystem surrounding their CMS, an ecosystem that they actually charge money for in order to participate. An ecosystem that you have jumped into with your own plugin contributions. Free or not has nothing to do with it.

If you are going to create something that rides the tails of a commercial product and put it out there for people to use in their projects, then make something that WORKS, instead of making them waste time going in circles trying to figure out why you apparently can't make your stuff not overwrite it's own files or behave as your own documentation indicates it should.
