### ISSUE TITLE
Composer Support

### ISSUE THREAD

**Issue by schnti** [distantnative/search-for-kirby#6]
Installation via Composer is mentioned in the documentation, but is not possible.

`Could not find a matching version of package distantnative/search-for-kirby. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).  
`

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1868482/72258626-d63d3900-360e-11ea-83f8-b8fe464a9676.png">

<img width="507" alt="image" src="https://user-images.githubusercontent.com/1868482/72258546-a2faaa00-360e-11ea-95e0-036115a0d0fa.png">

**Comment by distantnative** [comment]
It should work now (keep in mind that during the alpha you probably will have to adapt your setup to accept unstable versions: https://getcomposer.org/doc/04-schema.md#minimum-stability)
