### ISSUE TITLE
/vendor/autoload.php warning when installed with composer

### ISSUE THREAD

**Issue by philipmarnef** [distantnative/search-for-kirby#8]
I installed the plugin with composer, which places the dependencies at root/vendor. The include in `index.php` points to `__DIR__ . '/vendor/autoload.php'` however, so I run into errors when I try to run the index build shell script.

**Comment by philipmarnef** [comment]
My bad, this is apparently how you support both composer and non-composer installs and the Kirby guide suggest suppressing not found errors with `@include_once` instead. So the other errors I'm seeing are unrelated to this, will post another issue.

**Comment by distantnative** [comment]
FYI: I’m planning for this weekend to work on another alpha version. I haven’t overlooked this issue.

**Comment by distantnative** [comment]
✅ Fixed in next alpha release (1.0.0-alpha.3)
